"""Eastbridge Academy chess bot project — student kit."""

from chessdk.types import (
    BLACK,
    BISHOP,
    CastlingRights,
    Color,
    Kind,
    KING,
    KNIGHT,
    Move,
    MoveRecord,
    PAWN,
    Piece,
    QUEEN,
    ROOK,
    WHITE,
    opposite,
)
from chessdk.squares import (
    BISHOP_DIRECTIONS,
    KING_OFFSETS,
    KNIGHT_OFFSETS,
    ROOK_DIRECTIONS,
    QUEEN_DIRECTIONS,
    file_of,
    on_board,
    parse_square,
    rank_of,
    sq,
    square_name,
)
from chessdk.fen import STARTING_FEN, parse_fen

__all__ = [
    "BISHOP",
    "BISHOP_DIRECTIONS",
    "BLACK",
    "CastlingRights",
    "Color",
    "KING",
    "KING_OFFSETS",
    "KNIGHT",
    "KNIGHT_OFFSETS",
    "Kind",
    "Move",
    "MoveRecord",
    "PAWN",
    "Piece",
    "QUEEN",
    "QUEEN_DIRECTIONS",
    "ROOK",
    "ROOK_DIRECTIONS",
    "STARTING_FEN",
    "WHITE",
    "file_of",
    "on_board",
    "opposite",
    "parse_fen",
    "parse_square",
    "rank_of",
    "sq",
    "square_name",
]
